apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "image-registry-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{openshift_image_registry_pvc_size}}"
  volumeMode: Filesystem
