apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: {{nfs_subdir_external_provisioner_project_name}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: {{nfs_subdir_external_provisioner_name}}
            - name: NFS_SERVER
              value: {{nfs_subdir_external_provisioner_nfs_server_ipaddr}}
            - name: NFS_PATH
              value: {{nfs_subdir_external_provisioner_nfs_server_path}}
      volumes:
        - name: nfs-client-root
          nfs:
            server: {{nfs_subdir_external_provisioner_nfs_server_ipaddr}}
            path: {{nfs_subdir_external_provisioner_nfs_server_path}}
