apiVersion: v1
baseDomain: {{cluster_base_domain}}
compute:
- hyperthreading: Enabled
  name: worker
  # For VMWare UPI you must set the value of the replicas parameter to 0
  # replicas: {{groups[provision_group_workers] | length + groups[provision_group_infras] | length}}
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: {{groups[provision_group_masters] | length}}
metadata:
  name: {{cluster_name}}
networking:
  clusterNetworks:
  - cidr: {{cluster_pods_network}}
    hostPrefix: 23
  networkType: {{openshift_network_type}}
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    vcenter: {{vc_host}}
    username: {{vc_user_okd}}
    password: {{vc_password_okd}}
    datacenter: {{vc_datacenter}}
    defaultDatastore: {{vc_datastore}}
    folder: "/{{vc_datacenter}}/vm/{{cluster_name}}"
fips: false
pullSecret: '{{openshift_pull_secret}}'
sshKey: '{{ssh_pub_key}}'
