apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      application:
        maxAge: "{{openshift_cluster_logging_retention_application}}"
      infra:
        maxAge: "{{openshift_cluster_logging_retention_infra}}"
      audit:
        maxAge: "{{openshift_cluster_logging_retention_audit}}"
    elasticsearch:
      nodeSelector:
          node-role.kubernetes.io/infra: ""
      nodeCount: {{openshift_cluster_logging_es_node_count}}
      storage:
        storageClassName: "{{openshift_cluster_logging_es_sc_name}}"
        size: "{{openshift_cluster_logging_es_pvc_size}}"
      redundancyPolicy: "{{openshift_cluster_logging_es_redundancy}}"
  visualization:
    type: "kibana"
    kibana:
      nodeSelector:
          node-role.kubernetes.io/infra: ""
      replicas: 1
  curation:
    type: "curator"
    curator:
      nodeSelector:
          node-role.kubernetes.io/infra: ""
      schedule: "30 3 * * *"
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
